name: test config and do_commands on each commit

on:
  push:
    branches:
      - main
    paths:
      - '**/**.go'
      - 'Makefile'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '**/**.go'
      - 'Makefile'
      - '.github/workflows/test.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.13

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx264-dev git-lfs

    - name: Run tests
      run: make test
